source 'https://github.com/CocoaPods/Specs.git'

target 'StateKit', :exclusive => true do
  pod "StateKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "StateKit", :path => "../"

  pod 'Specta', '~> 0.2.1', :inhibit_warnings => true
  pod 'Expecta'
  pod 'OCMockito', '~> 1.0'
end