source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target :StateKitExample do
  pod 'StateKit', :path => "../"
end

target :Tests do
  pod 'StateKit', :path => "../"

  pod 'Specta', '~> 0.2.1', :inhibit_warnings => true
  pod 'Expecta'
  pod 'OCMockito', '~> 1.0'
end
