source 'https://github.com/CocoaPods/Specs.git'

target 'StateKit', :exclusive => true do
  pod "StateKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "StateKit", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'OCMock'
end